name: SRE Production Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Run Tests and Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt
        pip install pytest-cov black flake8

    - name: Code formatting check
      run: |
        cd app
        black --check .

    - name: Linting
      run: |
        cd app
        flake8 . --max-line-length=100

    - name: Run unit tests
      run: |
        cd app
        pytest --cov=. --cov-report=xml --cov-report=term